### ISSUE TITLE
Sending RTF data that isn't on a filesystem path

### ISSUE THREAD

**Issue by thegoatherder** [Fdawgs/node-unrtf#212]
### Prerequisites

- [X] I have written a descriptive title
- [X] I have searched existing feature requests to ensure it has not already been proposed

- [X] I agree to follow the [Code of Conduct](../../CODE_OF_CONDUCT.md) that this project adheres to

### Description

Hi! We have a database of RTF files. We can easily get the RTF into node.js using npm module `mssql`. Is there any way to feed this RTF data to `node-unrtf` without first creating a temporary file in the filesystem? We are using Linux to host the app.

For example:

```javascript
unRTF.convert(rtfData, {
  noPictures: true,
  outputText: true,
  inputFile: false // some flag which states that rtfData is a string containing RTF data to convert, not a path on filesystem
});
```

**Comment by thegoatherder** [comment]
Actually based on the comments in #2, it looks like `stdin` is not supported. You mentioned working on another solution which could handle `stdin` - did this get published?

**Comment by Fdawgs** [comment]
Hi @thegoatherder, sorry for the extremely late reply!
I was working on another solution as mentioned in #2 but was dragged into other work, so had to put it on the back burner.
I'm now able to revisit it, so will be taking a look over the coming weeks.

**Comment by thegoatherder** [comment]
Hi @Fdawgs! Thanks for this. We resorted to extracting the rtf content into a temp file on disk in the end - not ideal as it is more I/O than we'd like - especially in environments with heavy AV heuristics - extracting millions of small files onto disk plays havoc with AV CPU loads. 

It will be interesting to see if you can come up with a solution. Let me know if you need any help with testing etc.

FWIW we also tried to extract the text from RTF using a SQL Server CLR (C#) function (adapted from [this code](https://chrisbenard.net/2014/08/20/extract-text-from-rtf-in-c-net/). Throughput was amazing keeping everything in SQL Server end to end - but the quality of the text extract was nowhere near as good as the unrtf binary (linux version) - many document features failed to extract properly and resulted in sections of the original document not extracting at all.

**Comment by smcardle** [comment]
Hi
It's been a few months with no solution, so far, it seems.
Has there been any updates here regarding the passing in of stings rather than file paths as I have the exact same issue.
I decode base64 encode rtf content, from an API request, into strings and I really do not want to have to store that string in a file on the file system before converting that rtf string to HTML

**Comment by Fdawgs** [comment]
Unable to find any solution to this, sorry. The underlying binary only accepts a file path, not a buffer, stream, or any other input.

I would recommend rtf.js if this is essential functionality, as that supports other inputs (though it can't render tables).
