### ISSUE TITLE
bug: pictures are not saved to same directory as RTF file

### ISSUE THREAD

**Issue by calebchiam** [Fdawgs/node-unrtf#387]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported
- [X] I agree to follow the [Code of Conduct](https://github.com/fastify/.github/blob/main/CODE_OF_CONDUCT.md) that this project adheres to

### API/app/plugin version

5.0.3

### Node.js version

20.15

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.5

### Description

Many thanks for this v helpful package! As someone working in healthtech, this is a big help for reasons I'm sure you're familiar with given your work at NHS (:

I noticed that for the `noPictures` setting, the expected behaviour is that the embedded pictures get stored in the **directory of the original file.**

```
@property {boolean} [noPictures] Disable the automatic storing of embedded
 * pictures to the directory of the original file.
```

However, when I tested the package locally, it seems that the pictures get stored from the directory I run the RTF conversion from, rather than where the input file is stored.

### Steps to Reproduce

Create a file `temp.ts` with the below code and some RTF sample in subdirectory `./data/`.

```
import { UnRTF } from 'node-unrtf'

const f = async () => {
  const unRtf = new UnRTF()
  const html = await unRtf.convert(__dirname + `/data/rtf-sample.rtf`, {
    outputHtml: true,
    noPictures: false,
  })
  return html
}

console.log(f())
```

Run file with `ts-node temp.ts`.

### Expected Behaviour

`pict001.jpg` outputs to the local directory `.`, when it's expected to output to `./data`.

**Comment by calebchiam** [comment]
Based on the [`unrtf` docs](https://manpages.ubuntu.com/manpages/bionic/man1/unrtf.1.html)

> --nopict
              disables the automatic storing of embedded pictures to the current directory.

it looks like storing in the current directory is the expected behaviour, so this doesn't seem fixable.

**Comment by Fdawgs** [comment]
Hi @calebchiam, thanks for the report!

Good catch, looks like I documented that option incorrectly.
I will update it in the inline jsdoc tags, and review the rest of them whilst i'm at it, to ensure they are correct.

I'll also add an example to the readme for handling the images dumped into the current working directory.
