### ISSUE TITLE
Convert Option noPictures not working

### ISSUE THREAD

**Issue by olliebreeden** [Fdawgs/node-unrtf#81]
### Describe the bug

The option noPictures when set to true does not seem to do anything. I would expect this to not create files for pictures contained within the .rtf file but still creates the files when set to true or false.

### To Reproduce

unRTF.convert(file.Path, {
    noPictures: true,
    outputText: true,
  })

1. Run the conversion function
2. Output text is correct
3. .wmf Files are created which contain pictures within the .rtf file
4. Switching this to true or false does nothing.

### Expected behavior

Images are not created when set to true

### Desktop (please complete the following information)

-   OS: Windows
-   Version Windows 10
-   Node.js Version v14.17.0

**Comment by Fdawgs** [comment]
Thanks for the report @olliebreeden, this appears to be an issue with the UnRTF Windows binary itself and not the wrapper module.
`--nopict` is provided to the underlying binary, but is completely ignored 😕.
This is hopefully something that #2 will fix.
