### ISSUE TITLE
Can we connect?

### ISSUE THREAD

**Issue by thegoatherder** [Fdawgs/node-unrtf#90]
Hi Frazer. I'm working in a very similar space to you - one of our projects involves document text extraction and analysis in some NHS Trusts and we are using your `node-unrtf` project, among others in the pipeline. 

It would be really great if we could connect? I tried searching for you on linkedin... and your github profile doesn't have any contact details.

**Comment by Fdawgs** [comment]
Contact details are on my [profile readme](https://github.com/Fdawgs/Fdawgs) 😁  :

![image](https://user-images.githubusercontent.com/43814140/120979283-f837de00-c764-11eb-9d8c-7da75dd8e944.png)
